import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import 'aos/dist/aos.css';
import Header from './component/Header';
import AOSInit from './component/AOS';
import Footer from './component/Footer';
import Particles from './component/Particles';
import ConditionalLayout from './component/ConditionalLayout';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        suppressContentEditableWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-svh w-full text-secondary overflow-y-auto`}
      >
        <ConditionalLayout>{children}</ConditionalLayout>
      </body>
    </html>
  );
}
